# Generated by Django 2.0.2 on 2018-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
