# Generated by Django 2.0.2 on 2018-02-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usuario_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('estimacion_edad', models.IntegerField()),
                ('url_imagen', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_1', models.CharField(max_length=20)),
                ('apellido_2', models.CharField(max_length=20)),
                ('cedula', models.IntegerField()),
                ('hospital', models.CharField(max_length=20)),
            ],
        ),
    ]
